# src/Acme/ApiBundle/Resources/config/serializer/User.UserId.yml
Acme\CoreDomain\User\UserId:
    exclusion_policy: ALL
    properties:
        value:
            expose: true
            serialized_name: id
